# TOTAL SV SAMPLES = 530310443

##### GLobal settings
result_path: debug # results-chess-learn-KC
seed: 1

data_choice: chess_SV
train_num_sample: 2560

input_type: sensory
output_type: output
learnable_type: 'all' # 'betweenKC', 'withinKC', 'all'
num_heads: 1 # number of DPU to use
timesteps: 8 # RNN timesteps

#### Training configs
num_epoch: 10
use_steps:
num_steps: 100
num_steps_eval: 10
batch_size: 256
learning_rate: 0.0001
dropout_rate: 0.2


experiments:
#  DPU_Base_Unlearnable_residual:
#    init: droso
#    learnable: false
#    residual: true
#    model_choice: RNN
#
#  DPU_CNN_Unlearnable_RELU_residual: # add relu after conv layers
#    init: droso
#    learnable: false
#    residual: true
#    model_choice: CNN
#    num_conv: 1 # number of set of filters used in CNN probably 1 or 2.

  DPU_Base_Learnable_residual:
    init: droso
    learnable: true
    residual: true
    model_choice: RNN
  DPU_CNN_Learnable_RELU_residual: # add relu after conv layers
    init: droso
    learnable: true
    residual: true
    model_choice: CNN
    num_conv: 2 # number of set of filters used in CNN probably 1 or 2.